# Generated by Django 4.2.4 on 2023-09-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woerterbuch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buchstabe',
            options={'verbose_name_plural': 'Buchstaben'},
        ),
        migrations.AlterModelOptions(
            name='dialekt',
            options={'verbose_name_plural': 'Dialekte'},
        ),
        migrations.AlterModelOptions(
            name='wort',
            options={'verbose_name_plural': 'Wörter'},
        ),
        migrations.AddField(
            model_name='buchstabe',
            name='dialect',
            field=models.ForeignKey(blank=True, help_text='Bitte, wählen Sie eine Dialekte aus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buchstaben', to='woerterbuch.dialekt', verbose_name='Dialekt'),
        ),
        migrations.AddField(
            model_name='buchstabe',
            name='letter',
            field=models.CharField(default='-', max_length=1, verbose_name='Buchstabe'),
        ),
        migrations.AddField(
            model_name='dialekt',
            name='description',
            field=models.TextField(default='-', max_length=200, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='dialekt',
            name='slug',
            field=models.SlugField(default='Deutsch', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='dialekt',
            name='title',
            field=models.CharField(default='-', max_length=200, verbose_name='Dialekt'),
        ),
        migrations.AddField(
            model_name='wort',
            name='dialect',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='Dialekt', to='woerterbuch.dialekt', verbose_name='Dialekt'),
        ),
        migrations.AddField(
            model_name='wort',
            name='letter',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='Buchstabe', to='woerterbuch.buchstabe', verbose_name='Buchstabe'),
        ),
        migrations.AddField(
            model_name='wort',
            name='text',
            field=models.TextField(default='-', max_length=300, verbose_name='Wort'),
        ),
        migrations.AddField(
            model_name='wort',
            name='translation',
            field=models.TextField(default='-', max_length=900, verbose_name='Englisch'),
        ),
        migrations.AddField(
            model_name='wort',
            name='uebersetzung',
            field=models.TextField(default='-', max_length=900, verbose_name='Deutsch'),
        ),
    ]
