# Generated by Django 4.2.4 on 2023-09-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woerterbuch', '0002_alter_buchstabe_options_alter_dialekt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchstabe',
            name='letter',
            field=models.TextField(default='-', max_length=1, verbose_name='Buchstabe'),
        ),
        migrations.AlterField(
            model_name='dialekt',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='dialekt',
            name='title',
            field=models.TextField(default='-', max_length=200, verbose_name='Dialekt'),
        ),
    ]
