# Generated by Django 4.2.4 on 2023-09-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woerterbuch', '0003_alter_buchstabe_letter_alter_dialekt_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wort',
            name='dialect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dialekt', to='woerterbuch.dialekt', verbose_name='Dialekt'),
        ),
        migrations.AlterField(
            model_name='wort',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buchstabe', to='woerterbuch.buchstabe', verbose_name='Buchstabe'),
        ),
    ]
