# Generated by Django 4.2.4 on 2023-09-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woerterbuch', '0004_alter_wort_dialect_alter_wort_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchstabe',
            name='letter',
            field=models.TextField(max_length=1, verbose_name='Buchstabe'),
        ),
        migrations.AlterField(
            model_name='dialekt',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Dialekt'),
        ),
    ]
