# Generated by Django 4.2.4 on 2023-09-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woerterbuch', '0005_alter_buchstabe_letter_alter_dialekt_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wort',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Wort'),
        ),
        migrations.AlterField(
            model_name='wort',
            name='translation',
            field=models.TextField(max_length=900, verbose_name='Englisch'),
        ),
        migrations.AlterField(
            model_name='wort',
            name='uebersetzung',
            field=models.TextField(max_length=900, verbose_name='Deutsch'),
        ),
    ]
