# Generated by Django 4.2.4 on 2023-09-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woerterbuch', '0006_alter_wort_text_alter_wort_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchstabe',
            name='dialect',
            field=models.ForeignKey(help_text='Bitte, wählen Sie eine Dialekte aus', on_delete=django.db.models.deletion.CASCADE, related_name='Buchstaben', to='woerterbuch.dialekt', verbose_name='Dialekt'),
        ),
    ]
