# Generated by Django 4.2.4 on 2023-09-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woerterbuch', '0007_alter_buchstabe_dialect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchstabe',
            name='dialect',
            field=models.ForeignKey(blank=True, help_text='Bitte, wählen Sie eine Dialekte aus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buchstaben', to='woerterbuch.dialekt', verbose_name='Dialekt'),
        ),
        migrations.AlterField(
            model_name='wort',
            name='dialect',
            field=models.ForeignKey(blank=True, help_text='Bitte, wählen Sie eine Dialekte aus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dialekt', to='woerterbuch.dialekt', verbose_name='Dialekt'),
        ),
        migrations.AlterField(
            model_name='wort',
            name='letter',
            field=models.ForeignKey(blank=True, help_text='Bitte, wählen Sie eine Buchstabe aus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buchstabe', to='woerterbuch.buchstabe', verbose_name='Buchstabe'),
        ),
    ]
